catalog/urls.py
from django.conf.urls import url

from . import views


# url primeiro padrao, segundo a view, nome para ser utilizado nos templates
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'), #url amigavel parametrizada
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'), #url amigavel parametrizada
]

checkout/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem, name='create_cartitem'),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core import views
from catalog import views as views_catalog
# url primeiro padrao, segundo a view, nome para ser utilizado nos templates

from django.contrib.auth.views import login, logout
urlpatterns = [
    url(r'^$', views.index , name='index'),
    url(r'^contato/$', views.contact , name='contact'),
    url(r'^entrar/$', login, {'template_name': 'login.html'} , name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'} , name='logout'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),#namespace e
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    #url(r'^registro/$', views.register , name='register'),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug= models.SlugField('Identificador', max_length=100)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name= 'Categoria'
        ordering =['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug })
        #args sao parametros não nomeados, são posicionados
        #kwargs sao parametros nomeados

class Product(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug= models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Cateogira') #ajuda evitar imports
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=10)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)


    class Meta:
        verbose_name= 'Produto'
        ordering =['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Product, Category

# Create your views here.

class ProductListView(generic.ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    # Paginação
    # Automatica mente cria na url page = nume
    paginate_by = 2

product_list = ProductListView.as_view()

"""
def product_list(request):
    context = {
        'products': Product.objects.all()
    }
    return render(request, 'catalog/product_list.html', context)
"""
class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    paginate_by = 2

    def get_queryset(self):
        #category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Product.objects.filter(category__slug = self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()

"""
def category(request, slug):
    category = Category.objects.get(slug = slug)
    context = {
        'current_category': category ,
        'product_list': Product.objects.filter(category = category)
    }
    return render(request, 'catalog/category.html', context)
"""

def product(request, slug):
    product = Product.objects.get(slug= slug)
    context = {
        'product': product
    }

    return render(request , 'catalog/product.html', context)

catalog/templates/catalog/_product.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="{{ product.get_absolute_url }}">
            {% if product.image %}
            <img src="{{ product.image }}" alt="" />
            {% else %}
            <img src="http://placehold.it/350x250" alt="" />
            {% endif %}
        </a>
        <div class="caption">
            <h3>{{ product }}</h3>
            {{ product.description|linebreaks }}
            <p>
                <a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a>
                <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-default cart-item-add" role="button">Adicionar</a>
            </p>
        </div>
    </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}
{% load pagination %}

{% block title %}
  {{ current_category }} | {{ block.super }}
{% endblock %}
{% block container %}
<div class="page-header">
    <h1>{{ current_category }}</h1>
  </div>
  <div class="row">
    {% for product in product_list %}
    {% include "catalog/_product.html" %}


    {% endfor %}
  </div>
  {% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ product }}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
    <p>
      <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-sucess" role="button">Adicionar</a>
    </p>
      {{ product.description|linebreaks }}

  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}
{% load pagination %}

{% block title %}
  Listagem de Produtos | {{ block.super }}
{% endblock %}
{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
  </div>
  <div class="row">
    {% for product in product_list %}
      {% include "catalog/_product.html" %}
    {% endfor %}
  </div>
{% pagination request paginator page_obj %}
{% endblock %}